<?php

function wac_permission() {
  return array(
    'view web accessable charts' => array(
      'title' => t('View web accessible charts'),
      'description' => t('View any charts created by the Web Accesible Charts module.'),
    ),
    'administer web accessible charts' => array(
      'title' => t('Administer web accessible charts.'),
      'description' => t('Create and manipulate charts created by the Web Accesible Charts module.'),
    ),
  );
}

function wac_entity_info() {
  $info = array();
  $info['chart'] = array(
    'label' => t('Chart'),
    'base table' => 'wac',
    'entity keys' => array(
      'id' => 'cid',
      'bundle' => 'type',
      'label' => 'title'
    ),
    'entity class' => 'Entity',
    'controller class' => 'EntityAPIController',
    'module' => 'wac',
    'fieldable' => TRUE,
    'bundles' => array(),
    'bundle keys' => array(
      'bundle' => 'type',
    ),
    'view_modes' => array(
      'full' => array(
        'label' => t('Full chart'),
        'custom settings' => FALSE,
      ),
    )
  );
  $bundles = wac_get_chart_types();
  foreach ($bundles AS $key => $name) {
    $info['chart']['bundles'][$key] = array(
      'label' => $name,
      'admin' => array(
        'path' => 'admin/structure/chart/manage/%wac_chart_bundle',
        'real path' => 'admin/structure/chart/manage/' . $key,
        'bundle argument' => 4,
        'access arguments' => array('administer web accessible charts'),
      ), 
    );
  }
  return $info;
}

function wac_menu() {
  $items = array();
 /* $items['admin/structure/charts'] = array(
    
  );*/
  $items['chart/%wac_chart_entity'] = array(
    'title' => 'Chart',
    'page callback' => 'wac_chart_entity_view',
    'page arguments' => array(1),
    'access arguments' => array('view web accessable charts'),
    'type' => MENU_NORMAL_ITEM
  );
  $items['chart/%wac_chart_entity/view'] = array(
    'title' => 'View Chart',
    'page callback' => 'wac_chart_entity_view',
    'page arguments' => array(1),
    'access arguments' => array('view web accessable charts'),
    'type' => MENU_LOCAL_TASK,
    'weight' => 1
  );
  $items['chart/add/%wac_chart_bundle'] = array(
    'title' => 'Chart',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('wac_chart_add', 2),
    'access arguments' => array('administer web accessible charts'),
    'file' => 'wac.admin.inc',
    'file path' => drupal_get_path('module', 'wac') . '/includes',
    'type' => MENU_NORMAL_ITEM
  );
  $items['chart/%wac_chart_entity/edit'] = array(
    'title' => 'Edit Chart',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('wac_chart_add', 1),
    'access arguments' => array('administer web accessible charts'),
    'file' => 'wac.admin.inc',
    'file path' => drupal_get_path('module', 'wac') . '/includes',
    'type' => MENU_LOCAL_TASK,
    'weight' => 2
  ); 
  $items['chart/%wac_chart_entity/delete'] = array(
    'title' => 'Delete Chart',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('wac_chart_delete_confirm', 1),
    'access arguments' => array('administer web accessible charts'),
    'file' => 'wac.admin.inc',
    'file path' => drupal_get_path('module', 'wac') . '/includes',
    'type' => MENU_LOCAL_TASK,
    'weight' => 3
  );
  $items['admin/structure/chart/manage/%wac_chart_bundle'] = array(
    'title' => 'Administer Chart Type',
    'title callback' => 'wac_chart_type_title',
    'title arguments' => array(4),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('wac_chart_type_admin_form', 4),
    'access arguments' => array('administer web accessible charts'),
    'file' => 'wac.admin.inc',
    'file path' => drupal_get_path('module', 'wac') . '/includes',
    'type' => MENU_NORMAL_ITEM
  );
  return $items;
}

function wac_d3_lib() {
  $lib = array(
    'title' => 'D3',
    'website' => 'http://d3js.org',
    'version' => '3.3.13',
    'js' => array(
      'sites/all/libraries/d3/d3.min.js' => array(),
    )
  );
  return variable_get('wac_d3_lib', $lib);
}

function wac_library() {
  $lib = wac_d3_lib();
  return array('d3' => $lib); 
}

/**
 * We provide two chart theme functions wac_chart_entity for viewing the whole fielded entity.
 *   and wac_chart for rendering purely the chart visualization.
 */
function wac_theme($existing, $type, $theme, $path) {
  return array(
    'wac_chart_entity' => array(
      'path' => $path . '/theme',
      'template' => 'wac-chart-entity',
      'render element' => 'elements'
    ),
    'wac_chart' => array(
      'path' => $path . '/theme',
      'template' => 'wac-chart',
      'render element' => 'elements'
    )
  ); 
}

function template_preprocess_wac_chart_entity(&$variables) {
  $chart = $variables['elements']['#chart'];
  $langcode = $variables['elements']['#language'];
  $variables['view_mode'] = $variables['elements']['#view_mode'];
  // Helpful $content variable for templates.
  $variables += array('content' => array());
  foreach (element_children($variables['elements']) as $key) {
    $variables['content'][$key] = $variables['elements'][$key];
  }
  // Long last add the chart itself.
  $variables['content']['chart'] = array(
    '#theme' => 'wac_chart',
    '#chart' => $chart,
    '#language' => $langcode
  );
  // Make the field variables available with the appropriate language.
  field_attach_preprocess('chart', $chart, $variables['content'], $variables);
  $variables['theme_hook_suggestions'][] = 'wac-chart-entity__' . $chart->type;
  $variables['theme_hook_suggestions'][] = 'wac-chart-entity__' . $chart->cid;
}

function template_preprocess_wac_chart(&$variables) {
  $chart = $variables['elements']['#chart'];
  $langcode = $variables['elements']['#language'];
  $variables['chart_id'] = 'wac-' . $chart->cid;
  // For D3 do it this way so we can set the error easily.
  wac_chart_add_d3_library();
  // All we need to do is include a bunch of files settings
  $path = drupal_get_path('module', 'wac');
  drupal_add_css($path . '/theme/css/wac.css', array('type' => 'file', 'group' => CSS_DEFAULT));
  drupal_add_js($path . '/theme/js/class.js', array('type' => 'file', 'group' => JS_DEFAULT)); 
  drupal_add_js($path . '/theme/js/chart-base.js', array('type' => 'file', 'group' => JS_DEFAULT)); 
  switch($chart->type) {
    case 'bar':
      $chart->js_class = 'ChartBar';
      drupal_add_js($path . '/theme/js/chart-bar.js', array('type' => 'file', 'group' => JS_DEFAULT));
      break;
    case 'line':
      $chart->js_class = 'ChartLine';
      drupal_add_js($path . '/theme/js/chart-line.js', array('type' => 'file', 'group' => JS_DEFAULT));
      break;
    case 'pie':
      $chart->js_class = 'ChartPie';
      drupal_add_js($path . '/theme/js/chart-pie.js', array('type' => 'file', 'group' => JS_DEFAULT));
      break;
  }
  drupal_add_js($path . '/theme/js/chart-behavior.js', array('type' => 'file', 'group' => JS_DEFAULT));
  wac_chart_add_settings($chart, $variables['chart_id'], $langcode);
}

function wac_chart_add_settings($chart, $id, $l) {
  $settings = array();
  $settings['id'] = $id;
  $settings['class'] = $chart->js_class;
  // Dictionary acts as lookup for chart type.
  $settings['dictionary'] = array();
  if (!function_exists('wac_chart_fields')) {
    require_once(drupal_get_path('module', 'wac') . '/includes/wac.fields.inc');
  }
  $fields = wac_chart_fields();
  // We don't need the file
  unset($fields[$chart->type]['data_file']);
  $fields = array_keys($fields[$chart->type]);
  foreach($fields AS $key) {
    $settings['dictionary'][$key] = array();
    if (!empty($chart->{$key}[$l])) {
      foreach ($chart->{$key}[$l] AS $item) {
        $settings['dictionary'][$key][] = $item['value'];
      }
    }
  }
  $settings['dictionary']['title'] = $chart->title;
  $settings['dictionary']['type'] = $chart->type;
  // Data contains the actual data to render.
  $settings['data'] = wac_get_data_from_file($chart->data_file[$l][0]);
  drupal_add_js(array('wac' => array($settings)), array('type' => 'setting'));
}

function wac_chart_entity_view($chart) {
  return wac_chart_view_multiple(array($chart->cid => $chart));
}

function wac_chart_view_multiple($charts, $view_mode = 'full', $langcode = NULL) {
  entity_prepare_view('wac_chart', $charts, $langcode);
  field_attach_prepare_view('wac_chart', $charts, $view_mode, $langcode);
  $build = array();
  foreach ($charts as $chart) {
    $build['charts'][$chart->cid] = wac_chart_view($chart, $view_mode, $langcode);
  }
  return $build;
}

function wac_chart_view($chart, $view_mode = 'full', $langcode = NULL) {
  if (!isset($langcode)) {
    // @TODO inestigate what should be done here.
    $langcode = LANGUAGE_NONE;
  }
  wac_chart_build_content($chart, $view_mode, $langcode);
  $build = $chart->content;
  unset($chart->content);
  $build += array(
    '#theme' => 'wac_chart_entity',
    '#chart' => $chart,
    '#view_mode' => $view_mode,
    '#language' => $langcode,
  );
  $type = 'chart';
  drupal_alter(array('chart_view', 'entity_view'), $build, $type);
  return $build;
}

function wac_chart_build_content($chart, $view_mode, $langcode) {
  if (!isset($langcode)) {
    $langcode = $GLOBALS['language_content']->language;
  }
  $chart->content = array();
  // Allow modules to change the view mode.
  $context = array(
    'entity_type' => 'chart',
    'entity' => $chart,
    'langcode' => $langcode,
  );
  // Let other plugins change view mode
  drupal_alter('entity_view_mode', $view_mode, $context);
  // Build fields
  field_attach_prepare_view('chart', array($chart->cid => $chart), $view_mode, $langcode);
  entity_prepare_view('node', array($chart->cid => $chart), $langcode);
  $chart->content += field_attach_view('chart', $chart, $view_mode, $langcode);
  // Let folks alter chart with hook_entity_view
  module_invoke_all('entity_view', $chart, 'chart', $view_mode, $langcode);
  $chart->content += array('#view_mode' => $view_mode);
}

function wac_chart_entity_delete($chart) {
  $message = t('Deleted chart: ' . $chart->title);
  entity_delete('chart', $chart->cid);
  drupal_set_message($message, 'status');
  drupal_goto('<front>');
}

function wac_chart_entity_load($cid) {
  $chart = entity_load('chart', array((int) $cid));
  return !empty($chart) && !empty($chart[$cid]) ? $chart[$cid] : FALSE;
}

function wac_chart_bundle_load($type) {
  $query = db_select('wac_type', 'types');
  $query->fields('types', array('title', 'type'));
  $query->condition('type', $type, '=');
  $resource = $query->execute();
  $result = $resource->fetchAll();
  if (!empty($result)) {
    return $result[0];
  }
  return FALSE;
}

function wac_chart_type_title($type) {
  return $type->title;
}

function wac_get_chart_types() {
  return array(
    'bar' => t('Bar Chart'),
    'line' => t('Line Chart'),
    'pie' => t('Pie Chart')
  );
}

function wac_chart_add_d3_library() {
  $lib = wac_d3_lib();
  $lib_js = array_keys($lib['js']);
  $path = $lib_js[0];
  if (!file_exists($path)) {
    drupal_set_message(t("The D3 library was missing from your site's libraries directory. Please download D3 and place it in !path.", array('!path' => $path)), 'error');
  }
  else {
    drupal_add_library('wac', 'd3');
  }
}

function wac_get_data_from_file($file) {
  if (is_array($file)) {
    $file = (object) $file;
  }
  $path = file_create_url($file->uri);
  $ext = substr($path, strrpos($path, '.') + 1, strlen($path));
  $handle = fopen($path, "r");
  if ($handle !== FALSE) {
    switch ($ext) {
      case 'csv':
        $data = wac_get_data_from_delimiter_seperated_value_file($handle, ','); 
        break;
      case 'tsv':
        $data = wac_get_data_from_delimiter_seperated_value_file($handle, '	');
        break;
      case 'json':
        $data = wac_get_data_from_json_file($handle);
        break;
    }
    fclose($handle);
  }
  return $data;
}

function wac_get_data_from_delimiter_seperated_value_file($handle, $delimiter) {
  $output = array();
  while (($data = fgetcsv($handle, 0, $delimiter)) !== FALSE) {
    $output[] = $data;
  }
  return $output;
}

function wac_get_data_from_json_file($handle) {
  while (!feof($handle)) {
    $data = fgets($handle);
    return (array) json_decode($handle);
  }
  return FALSE;
}
